services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_DOMAIN=https://courses-top.ru
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_DOMAIN=https://courses-top.ru
    restart: unless-stopped

