import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import { Footer, Sidebar, Up } from "../components";
import cn from 'classnames';
import { HeaderWrapper } from "../components/Header/HeaderWrapper";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(notoSans.className, styles.wrapper)}>
          <HeaderWrapper />
          <Sidebar className={styles.sidebar} />
          <main className={styles.body}>{children}</main>
          <Footer className={styles.footer} />
          <Up />
      </body>
    </html>
  );
}
