name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Sync and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # SSH settings
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          
          # Files synchronization
          rsync -avz --delete --exclude='.git' ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/opt/docker/courses-app/
          
          # Application deployment
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "
            cd /opt/docker/courses-app &&
            export DOCKER_CLIENT_TIMEOUT=600 &&
            export COMPOSE_HTTP_TIMEOUT=600 &&
            export DOCKER_BUILDKIT=1 &&
            docker-compose build app --no-cache &&
            docker-compose down &&
            docker-compose up -d
          "
          
          # SSH key cleanup
          rm -f ~/.ssh/id_rsa